enum FormActionTypes {
    GET_FORM_DETAIL_SUCCESS = 'GET_FORM_DETAIL_SUCCESS',
    GET_FORM_DETAIL_PENDING = 'GET_FORM_DETAIL_PENDING',
    GET_FORM_DETAIL_ERROR = 'GET_FORM_DETAIL_ERROR',
    SUBMIT_FORM_SUCCESS = 'GET_FORM_DETAIL_SUCCESS',
    SUBMIT_FORM_PENDING = 'GET_FORM_DETAIL_PENDING',
    SUBMIT_FORM_ERROR = 'GET_FORM_DETAIL_ERROR',
}

export default FormActionTypes
